[package]
name = "emu8085"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
eframe = "0.32.1"
egui = "0.32.1"
log = "0.4.27"
thiserror = "2.0.12"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.77"

[lib]
crate-type = ["cdylib", "rlib"]
