[package]
name = "emu8085"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
eframe = { version = "0.32.1", default-features = false, features = ["glow", "x11"] }
egui = { version = "0.32.1", default-features = false, features = [] }
log = "0.4.27"
thiserror = "2.0.12"
